import { chromium } from '@playwright/test';
import fs from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const results = [];
await fs.mkdir('.impeccable/review', { recursive: true });
for (const [name, width, height] of [['desktop',1440,1000], ['mobile',390,844], ['tablet',768,1024], ['small-mobile',320,740]]) {
 const page = await browser.newPage({ viewport: { width, height }, reducedMotion: 'reduce' });
 const errors = []; page.on('pageerror', e => errors.push(e.message));
 await page.goto('http://localhost:3000', { waitUntil: 'networkidle' });
 await page.screenshot({ path: `.impeccable/review/${name}-light.png`, fullPage: true });
 if (name === 'desktop' || name === 'mobile') await page.screenshot({ path: `.impeccable/review/${name}-hero.png` });
 const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
 const heroButtonBottom = await page.locator('.hero .primary-button').evaluate(e => e.getBoundingClientRect().bottom);
 await page.getByRole('button',{name:'Toggle light and dark mode'}).click();
 const dark = await page.locator('html').getAttribute('data-theme');
 await page.screenshot({ path: `.impeccable/review/${name}-dark.png`, fullPage: true });
 await page.reload({waitUntil:'networkidle'});
 const persistedTheme = await page.locator('html').getAttribute('data-theme');
 await page.getByRole('button',{name:'Toggle light and dark mode'}).click();
 await page.locator('.hero input').fill('test@example.com');
 await page.locator('.hero .primary-button').click();
 await page.getByText('Signups are temporarily unavailable. Please try again later.').waitFor();
 await page.locator('.ghost-button').click();
 await page.waitForURL('**/#waitlist-cta');
 results.push({ name, overflow, heroButtonBottom, viewportHeight: height, errors, dark, persistedTheme, formError: true, ctaNavigation: true });
 await page.close();
}
const motion = await browser.newPage({viewport:{width:1440,height:1000}});
await motion.goto('http://localhost:3000');
await motion.locator('.hero-demo[data-phase="proposal"]').waitFor();
await motion.locator('.hero-demo').screenshot({path:'.impeccable/review/editor-proposal.png'});
await motion.getByRole('button',{name:'Accept edit',exact:true}).click();
await motion.locator('.hero-demo[data-phase="accepted"]').waitFor();
await motion.getByRole('button',{name:'Replay editor preview'}).click();
await motion.locator('.hero-demo[data-phase="proposal"]').waitFor();
await motion.getByRole('button',{name:'Revert',exact:true}).click();
await motion.locator('.hero-demo[data-phase="reverted"]').waitFor();
results.push({ demoAccept: true, demoRevert: true, replay: true });
await fs.writeFile('.impeccable/review/results.json', JSON.stringify(results,null,2));
console.log(JSON.stringify(results,null,2));
await browser.close();
